# Generated by Django 5.2.5 on 2026-03-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkdata",
            name="link_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
