# Generated by Django 5.2.5 on 2026-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0002_alter_linkdata_link_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_color",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
