# Generated by Django 5.2.5 on 2026-03-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0004_category_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkdata",
            name="link_purpose",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
