# Generated by Django 5.2.5 on 2026-03-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0005_alter_linkdata_link_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="user_avatar",
            field=models.ImageField(blank=True, null=True, upload_to="user/avatar/"),
        ),
    ]
