# Generated by Django 5.2.5 on 2026-03-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0006_users_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
